### ISSUE TITLE
It takes too long to fill the Ad often, up to 60 seconds

### ISSUE THREAD

**Issue by mrbodich** [AppLovin/AppLovin-MAX-Swift-Package#12]
#### When requesting the Ad, there is 3 possible results I have.
1. Ad is loaded quickly
2. Ad is loaded after 10 or 20 or more seconds
3. Ad is not loaded after 60 seconds, so it fails with not-filled error

#### Expected:
Quick result — filled or no

#### Bidder Networks selected:
- AppLovin
- AppLovin Exchange

Here is what error AppLovin returns on 60 seconds timeout
```
[MAError: code=204, message=MAX returned no eligible ads from any mediated networks for this app/device, mediatedNetworkErrorCode=-1, mediatedNetworkErrorMessage=]
```

Does it possible to find a solution/fix for this? We could just load another ad on fail, but we have to wait 60 seconds.
Same behavior we have on both `Android` and `iOS`.

**Comment by mrbodich** [comment]
@thomasmso Is there any way to disable retries?
60 sec delay is not expected for us anyway, and we would like to get immediate result. Such delays make no sense for us especially in scrollable list, the user will never see this Ad.

**Comment by thomasmso** [comment]
@mrbodich - yeah, you can set an SDK extra parameter `"disable_auto_retries"` to `"true"`. Example code:

```
let configuration = ALSdkInitializationConfiguration(sdkKey: <your sdk key>) { builder in
    builder.mediationProvider = "max"
}
               
let sdk = ALSdk.shared()
sdk.settings.setExtraParameterForKey("disable_auto_retries", value: "true")
sdk.initialize(with: configuration) { configuration in
    ...    
}
```

**Comment by mrbodich** [comment]
Thanks @thomasmso !
