### ISSUE TITLE
CMP Name - No value set, when using Sourcepoint

### ISSUE THREAD

**Issue by mrbodich** [AppLovin/AppLovin-MAX-Swift-Package#13]
Almost always, I can't understand how to reproduce (same code, same simulator, try both fresh build and reinstall), AppLovin initializes without detecting CMP, showing `CMP Name - No value set `.
Sometimes AppLovin can detect it and shows `CMP Name - Sourcepoint Dialogue CMP`.

Yesterday it detected Sourcepoint every time, today never detects it.
Can you help us to fix it please?

- Initializing AppLovin after Sourcepoint
- Tried both simulator and real device
- Tried to set delay after the app launch before starting all initializations (just in case)

UPD: Now AppLovin detects Sourcepoint again, just randomly doing actions I have found that if I tap Accept ALL in Sourcepoint, then AppLovin can't detect Sourcepoint. I can accept multiple times and no result. But if I tap Save Selection button, then AppLovin will detect Sourcepoint after that. No matter which settings was selected in Sourcepoint, I can just show the already selected dialog and tap Save Selection, and AppLovin will detect Sourcepoint well after that, though no settings was changed.

**Comment by wootaejeon** [comment]
Hi @mrbodich, thanks for reporting the issue. Would you able to share the related logs (any logs from Sourcepoint and our verbose logs with tag `ALTCFManager`) when you tap Accept ALL?

**Comment by mrbodich** [comment]
Hey @wootaejeon 
I have prepared the Demo App which contains Sourcepoint _(see the link at the bottom)_.
All you have to do is get this parameters by creating Sourcepoint account

- CONSENT_ACCOUNT_ID
- CONSENT_PROPERTY_ID
- CONSENT_PROPERTY_NAME
- CONSENT_GDPR_PRIVACY_MANAGER_ID

Then in the project
- fill parameters for Creds object initialization in ALAppDelegate.swift file
- In project settings, `AppLovin MAX Demo App - Swift` target, Signing & Capabilities tab
  - set bundle identifier to your existing app from App Store (If you want to run on the real device)
  - Set your development team associated with the bundle (If you want to run on the real device)

Real `adUnitId` is not required to just test initialization, but we have issues displaying ads in EU, possible because of Sourcepoint trouble, we have to fix the current problem at the moment.

[AppLovin+Sourcepoint Demo App.zip](https://github.com/user-attachments/files/16683291/AppLovin%2BSourcepoint.Demo.App.zip)

**Comment by wootaejeon** [comment]
@mrbodich Before I try it out, can you try reading the TC data from UserDefaults which should have been written by Sourcepoint by the time you finish their prompt? Here is the [link](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#what-is-the-cmp-in-app-internal-structure-for-the-defined-api) to the IAB documentation with the keys. 

Main ones to check are `IABTCF_CmpSdkID`, `IABTCF_gdprApplies`, `IABTCF_TCString` and `IABTCF_VendorConsents`.

**Comment by mrbodich** [comment]
Hi @wootaejeon 
Thank you for sharing this info, we have investigated with the Sourcepoint team and in some specific cases their SDK failed to write these settings to UserDefaults.
So, I believe you can close this issue and it is a Sourcepoint bug.
