### ISSUE TITLE
Could not resolve package dependencies: checksum of downloaded artifact of binary target 'AppLovinSDK' 

### ISSUE THREAD

**Issue by UtkuDalmaz** [AppLovin/AppLovin-MAX-Swift-Package#2]
After the last update I am having

Could not resolve package dependencies: checksum of downloaded artifact of binary target 'AppLovinSDK' (06606a62ead9c6cd158c51a6c2ebaeed35cb7ccfafaf685c815e7860f2ad7225) does not match checksum specified by the manifest (d4fc7375c4a1291f7a5e9450e42b658d2d6b4c082115c4dcfbded0896d78255f) fatalError

When try to build with Xcode Cloud

**Comment by thomasmso** [comment]
Hi @UtkuDalmaz - this was broken in v11.5.1 of our SDK release. We will address it in v11.5.2 (eta next week).

**Comment by oliedis** [comment]
Getting the same error when building in Xcode (none cloud version)

**Comment by Djibs** [comment]
Same error

**Comment by mqaiserbutt** [comment]
@thomasmso any update on release of SDK v11.5.2 ?

**Comment by thomasmso** [comment]
@mqaiserbutt - likely EoW, we'll post the release here if you want to watch the repo: https://github.com/AppLovin/AppLovin-MAX-SDK-iOS

**Comment by thomasmso** [comment]
We just released SDK v11.5.2 which fixes this issue. Thank you for your patience.
