### ISSUE TITLE
How can I add mediated networks using SPM

### ISSUE THREAD

**Issue by lionel-alves** [AppLovin/AppLovin-MAX-Swift-Package#5]
Hi,

Thanks for supporting SPM as it create build error when using both Cocoapods and SPM since you can very quickly have the same dependencies appear in both. (like Google Utilities for example)

I was wondering how can we integrate mediated networks using SPM?

Thanks a lot!

**Comment by cameroneubank** [comment]
Would love to see more support for this! Any updates for giving this any priority?

**Comment by Arideno** [comment]
Hello, any progress on this? The Cocoapods are deprecated now.
