### ISSUE TITLE
App upload issues after updating to SDK v12.3.0 in XCode 15.3

### ISSUE THREAD

**Issue by kamalk2** [AppLovin/AppLovin-MAX-Swift-Package#6]
Updated to Xcode 15.3 and AppLovin SDK 12.3.0.
Getting the error in screenshot attached, while trying to upload the build to AppStore. Tried clearing package cache and resetting too. Info.Plist file contains all the fields mentioned in the error and no other code changes have been done before the Xcode and SDK updates. The code runs on Simulator with no issues.

![Screenshot 2024-03-08 at 7 37 39 PM](https://github.com/AppLovin/AppLovin-MAX-Swift-Package/assets/8474562/360ca338-fe42-4e14-b4aa-291a7da9a0f8)

**Comment by thomasmso** [comment]
Hey @kamalk2 - Thanks for bringing this up to us. We'll check it out and get back to you here next week.

**Comment by kamalk2** [comment]
@thomasmso I have an update. The same AppLovin SDK v12.3.0 functions with no errors on XCode 15.0.1. So issue is specific to XCode 15.3 + AppLovin 12.3.0

**Comment by ritamsarmah** [comment]
Hi @kamalk2, thanks for sharing that. I can confirm that this issue seems specific to some change in Xcode 15.3.

We're looking into fixing it soon; in the meantime, the best workaround will be to use Xcode 15.2.

**Comment by ritamsarmah** [comment]
Could you also share any other dependencies you've included in your project? Seems the Xcode 15.3 changes have also affected [Firebase](https://github.com/firebase/firebase-ios-sdk/issues/12441) and other packages, so you may need to update those as well to fully resolve those errors.

**Comment by kamalk2** [comment]
@ritamsarmah thanks for the update. I am using XCode 15.2 temporarily to create and upload Archives. I have attached the list of Dependencies I have in my project and Firebase is already updated to the latest recommended version which contains the fix.

![Screenshot 2024-03-12 at 9 10 30 AM](https://github.com/AppLovin/AppLovin-MAX-Swift-Package/assets/8474562/092885ec-9bbf-46e3-b578-cc50cbbe99d3)

**Comment by kamalk2** [comment]
@ritamsarmah I'm support only iOS 16+ and watchOS 9+

**Comment by ritamsarmah** [comment]
@kamalk2 we'll be pushing an SDK with some fixes for this soon. In the meantime you can workaround this by adding the missing `Info.plist` items manually:

1. Under **Package Dependencies**, right-click the "AppLovinSDK" package and click "Show in Finder".
2. Go up one directory to the parent (`SourcePackages/`)
3. Navigate to `artifacts/applovin-max-swift-package`.
4. Update the file at `./AppLovinSDK/AppLovinSDK.xcframework/ios-arm64/AppLovinSDK.framework/Info.plist` to include the following:

```xml
<key>CFBundleShortVersionString</key>
<string>12.3.0</string>
<key>CFBundleVersion</key>
<string>12030099</string>
```

Xcode 15.3 also seems to have a bug with the minimum OS version validation. This is affecting other SPM packages as well and is something we'll have to wait for Apple to fix separately. The current workaround is to modify the `MinimumOSVersion` in the same `Info.plist` from above to some really high value:

```xml
<key>MinimumOSVersion</key>
<string>100</string>
```

Let me know if the solution works for you and if you have any further questions.

**Comment by kamalk2** [comment]
@ritamsarmah I followed your instructions and edited the Info.Plist file. Then I tried twice to upload the archives and still getting the same issues. Please refer to the attached screenshots. The GoogleAppMeasurement errors are gone now after updating to Firebase's latest SDK.  I'll wait for your SDK update. Thanks.

![Screenshot 2024-03-13 at 10 28 32 AM](https://github.com/AppLovin/AppLovin-MAX-Swift-Package/assets/8474562/3a295d36-ac71-44ac-a2c8-d78f7ea4be2e)
![Screenshot 2024-03-13 at 10 29 12 AM](https://github.com/AppLovin/AppLovin-MAX-Swift-Package/assets/8474562/39428087-e4cd-4cad-a223-a80464d414a1)

**Comment by ritamsarmah** [comment]
@kamalk2, it seems the issue you might've edited the incorrect `Info.plist`. That looks like the one directly in `AppLovinSDK.xcframework`; however, there are additional `Info.plist` files under the separate architecture directories, e.g., `ios-arm64/AppLovinSDK.framework/Info.plist` is the one you need to modify.

**Comment by thomasmso** [comment]
We just pushed iOS SDK v12.3.1 which fixes this issue.

**Comment by kamalk2** [comment]
@thomasmso and @ritamsarmah there is still 1 issue about minimum app version. Please refer to the attached screenshot.

Do I have to follow the steps suggested by @ritamsarmah  again to fix this ?

![Screenshot 2024-03-18 at 9 44 52 AM](https://github.com/AppLovin/AppLovin-MAX-Swift-Package/assets/8474562/a6a593bd-0b2e-43d7-b1bb-2c431d785253)

**Comment by thomasmso** [comment]
@kamalk2 - What's your app'a min OS version?

**Comment by ritamsarmah** [comment]
Hi @kamalk2, yes, though only this change is required:

```xml
<key>MinimumOSVersion</key>
<string>100</string>
```

The "minimum OS version" error seems to be an Apple bug, since they _should_ allow third-party SDKs to support a lower minimum OS version than the app's. Currently, Xcode 15.3 requires the SDK's minimum OS version to equal (or exceed) the app's, which is an impractical requirement (i.e., since your app targets 16+, we'd need to have 16.0 in our plist).

Hopefully it will be resolved in the next Xcode patch release.
