### ISSUE TITLE
Test mode interstitial ad error

### ISSUE THREAD

**Issue by arijit006** [AppLovin/AppLovin-MAX-Swift-Package#7]
Getting the following error on Test mode for AppLovin Interstitial Ads.
(No such error when using test mode for other mediated networks. Checked on live as well - once with AppLovin and once with another network - no issues, ads are being loaded.)

![IMG_0090](https://github.com/AppLovin/AppLovin-MAX-Swift-Package/assets/137792334/827a1b9c-74f7-41ca-88ea-290df1225085)

**Comment by avi-cramer** [comment]
Hi @arijit006, we are aware of the issue and looking to fix it soon. I will post an update when the fix is in place.

**Comment by arijit006** [comment]
@avi-cramer Awesome! Sure thing.

**Comment by richashukla23** [comment]
@arijit006 this issue has been fixed now.

**Comment by richashukla23** [comment]
Hi, This issue has been fixed now!
