### ISSUE TITLE
Incorrect checksum for release 12.6.0

### ISSUE THREAD

**Issue by dpgmedia-bsellar** [AppLovin/AppLovin-MAX-Swift-Package#8]
Hello,

The Package.swift file has a check sum of `882080126b572d55f0991252d343eb7c6b6b98bde701912faf4317608bb7540a`.
But the [zip](https://artifacts.applovin.com/ios/com/applovin/applovin-sdk/AppLovinSDK-12.6.0.xcframework.zip) used by the release has a check sum of `5d25693ba8feb3d4b10ba0d9c596331ecc9b94995785ed1ed91cb7910ded5c7e`.

Xcode is unable to resolve the dependency correctly and this is blocking our app from compiling.

`Could not resolve package dependencies:
  checksum of downloaded artifact of binary target 'AppLovinSDK' (5d25693ba8feb3d4b10ba0d9c596331ecc9b94995785ed1ed91cb7910ded5c7e) does not match checksum specified by the manifest (882080126b572d55f0991252d343eb7c6b6b98bde701912faf4317608bb7540a)`

Could you fix this quickly ?

Thanks

**Comment by ritamsarmah** [comment]
Hi @dpgmedia-bsellar, thanks for bringing this to our attention. We've fixed the 12.6.0 release to use the correct checksum.
