### ISSUE TITLE
MAAdView subview background becomes black after Ad loaded

### ISSUE THREAD

**Issue by mrbodich** [AppLovin/AppLovin-MAX-Swift-Package#9]
I want a transparent MAAdView background (or white, or dynamic color), but it contains ALAdView subview which background is set to black once Ad is loaded.
<img width="424" alt="Screenshot 2024-07-29 at 10 52 48 PM" src="https://github.com/user-attachments/assets/e73c16ba-e300-40aa-a07d-1434130b44b8">
Even if I set it to nil, it's anyway will be set to black once the Ad is loaded (if i set it after the Ad is loaded, it works).
```
DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
    bannerView.subviews[1].backgroundColor = .none //bannerView is MAAdView
}
```
Our design does not have black frames around the banner)))

Is it any way to set the color I want and I have just missed that in docs (I've tried to find)?
Or if no, can you fix that, and remove the piece of logic which sets its color to black in the next SDK update?

Thanks.

**Comment by thomasmso** [comment]
@mrbodich - This isn't something that is configurable in our SDK. Most of our live creatives will span the width of the banner anyways. Another option is to set the width to 320pts or 728pts.

**Comment by mrbodich** [comment]
Yes, I can take the size of the loaded Ad, and fit the parent view precisely so I don't see that black background.
But anyway, why it's black and not transparent? I can put any color I want by myself, but I can't remove black. If someone needs black it's super easy to make.
I mean why not white or not pink, when every project has different designs and color palettes.

I understand it's not configurable, but...
If it's possible to fix, then I believe would be great to put transparent there in the next SDK update.

PS: 
1. adFormat of .banner is centered inside larger frame, when .mrec is aligned to top-left.
2. After banner loaded, and set that black background, it can reload occasionally and just make piece of background transparent. Then sometimes it can put that black bg again. And if reloading is not instant, and the Ad disappears for a portion of second, I see black background even if my parent view fits precisely.
3. On the last video you can see even more strange Ad transition. After the .mrec ad was aligned to the top-left, another one appears on top of it, with different alignment, and then black background becomes fully transparent!

* Yellow background is just a background applied to the parent view to see the bounds on the example.

I really hope you can fix that. Thank you.

<img width="322" alt="Screenshot 2024-07-30 at 9 11 52 PM" src="https://github.com/user-attachments/assets/928d1333-bd34-4ec3-a311-03b119ee8b12">

<img width="317" alt="Screenshot 2024-07-30 at 9 14 34 PM" src="https://github.com/user-attachments/assets/23887678-340d-401d-9ff0-74599b053e60">

https://github.com/user-attachments/assets/951c4073-18e0-4b5d-9aa9-4a016c7387bc


https://github.com/user-attachments/assets/4cc97f3f-196f-4a89-97c2-500f4b7cb0d0

**Comment by mrbodich** [comment]
And even if I fit the parent view precisely, the Ad appearance is blinking with that black background which definitely does not look nice. Every time before the Ad contents appears, I see that black rectangle blinking for 1-2 frames.

https://github.com/user-attachments/assets/0747f5b4-8bbf-47aa-a1f3-bfc0730ed739

**Comment by mrbodich** [comment]
I am not sure also about this recommendation in docs. This just doesn't work (I've tried), because the black background appears in the subview which is covering `adView`. So, if I set any background, I anyway have a black background which comes from the subview I've mentioned.

On the other hand you say
> This isn't something that is configurable in our SDK
But you have put the background configuration into your docs, which makes no sense and does not work because of black overlaying background of subview.

Considering the next piece of documentation  definitely can only see that black background as a bug.

<img width="652" alt="Screenshot 2024-07-31 at 9 56 48 AM" src="https://github.com/user-attachments/assets/b455878f-136d-4aa2-a98b-e2d09557785e">

**Comment by thomasmso** [comment]
The issue you're observing is isolated to some ads served by AppLovin, including the test ad you're seeing. The `MAAdView` container stretches certain underlying ad networks' ads to fit its width, and how the content is stretched varies from network to network. In this case, the ad is stretched to the width of the screen, with black used to fill in the sides.

I can offer a solution in the next SDK release that allows you to configure the `UIColor` of the sides. How does that sound?

In the meantime, you can set the `MAAdView` to have the minimum required width for banners: 320pts on phones and 728pts on tablets. You can conveniently retrieve these values using our APIs: `MAAdFormat.banner.size.width` and `MAAdFormat.leader.size.width`.

Regarding the documentation you referenced, the `backgroundColor` you set will only become visible for certain demand sources that require MAX _not_ to stretch their ads to the width of the container.

**Comment by mrbodich** [comment]
@thomasmso 

#1.
I don't have any troubles fitting the received Ad size, MAAd type has a size property which contains the actual size of the returned Ad which is the most accurate way to grab the size. Especially considering the fact that even if I request banner, AppLovin can return mrec, so no guarantee I get what I request. So, using received MAAd object's ad.size can't be better I believe. I never want to use (and will not ever use) any hardcoded sizes because it's definitely bad practice.

All I need is to get rid of that black background which is 100% a UIKit thing, and I am able to set that color to another after the Ad is presented. I believe it was just a piece of logic added by some developer and does nothing with the type of ad etc.
Aa I said, I am capable to set the background color to the view, and that black bg definitely looks like something unwanted, and especially it even works buggy.

So, my proposal - just remove that piece of code which sets the background to black and that's all.
Black bg is set at some point after the ad is loaded, right before it's presented in the view.

#2.
All that videos I have created are to show all bugs I have found, and to better present the black background color. The second bug is that alignment bug, which I don't care about. I fit the parent view in my real code to the Ad size, so it's just for you so you can know where you have bugs. Just try AdMob and make the view larger than the Ad, and you will get a reference of how it should work (simply centered always, and no any background).
